# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Ronnybest.SonarHotkeys
PackageVersion: 3.0.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: wix
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{EC6D0426-A723-4038-AE6A-3941CA85D339}'
ReleaseDate: 2026-10-01
AppsAndFeaturesEntries:
- DisplayName: SonarHotkeys
  Publisher: Danil
  ProductCode: '{EC6D0426-A723-4038-AE6A-3941CA85D339}'
  UpgradeCode: '{1F9112C0-EC56-405F-A1BA-788764B40E80}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Ronnybest/SonarHotkeys/releases/download/v3.0.0/SonarHotkeys-win-x64.msi
  InstallerSha256: 1CCEC6F71F3E522E6C8633B97DC7748C6A2D0FAC8C8CE630404BC3094B8B880F
ManifestType: installer
ManifestVersion: 1.12.0
